### ISSUE TITLE
I want to install x-pack, and set password, but it failed.

### ISSUE THREAD

**Issue by TerrificMao** [miztiik/elk-stack#1]
I want to install x-pack, and set password, but it failed.

[root@ip-172-16-xx-xx bin]# pwd
/usr/share/elasticsearch/bin
[root@ip-172-16-xx-xx bin]# ./elasticsearch-plugin install x-pack
ERROR: this distribution of Elasticsearch contains X-Pack by default

**Comment by miztiik** [comment]
The error message above says, X-Pack is there by default! What do you mean by _failed_.

**Comment by TerrificMao** [comment]
Thanks so much for your reply. I have followed your guide and installed the ELK on Amazon EC2 instance successfully, and next, i want to setup password on elasticsearch node.

[root@ip-172-16-xx-xx bin]# pwd
/usr/share/elasticsearch/bin
[root@ip-172-16-xx-xx bin]# ./elasticsearch-setup-passwords interactive

Unexpected response code [403] from calling GET http://172.16.-xx-xx:9200/_xpack/security/_authenticate?pretty
It doesn't look like the X-Pack security feature is available on this Elasticsearch node.
Please check if you have installed a license that allows access to X-Pack Security feature.

ERROR: X-Pack Security is not available.

**Comment by TerrificMao** [comment]
Sorry, ELK 6.4 version now already installed the x-pack, and I just need to start a 30-day trial and then setup the passworld. Thanks again.
